### ISSUE TITLE
no_agent branch broken by a test sentence

### ISSUE THREAD

**Issue by remo-help** [clulab/tomcat-text#117]
In the no_agent branch, the following sentence throws a "scala.NotImplementedError":

"Green, do you see any rubble here? "

I assume this has something to do you with dependencies traversing the new agent attachments. I will paste the full error code below:

`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: scala.NotImplementedError: an implementation is missing]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: java.lang.RuntimeException: scala.NotImplementedError: an implementation is missing
        at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:422)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
        at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:297)
Caused by: scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
        at org.clulab.asist.TomcatActions.mkAgent(TomcatActions.scala:80)
        at org.clulab.asist.TomcatActions.$anonfun$convertAgent$3(TomcatActions.scala:38)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.clulab.asist.TomcatActions.convertAgent(TomcatActions.scala:38)
        at org.clulab.asist.TomcatActions.$anonfun$convertAgents$1(TomcatActions.scala:32)
`

**Comment by remo-help** [comment]
The merged change has fixed the issue, thanks
