### ISSUE TITLE
ExtractDirSearch errors, redux

### ISSUE THREAD

**Issue by adarshp** [clulab/tomcat-text#6]
@pelovett - I'm still getting an error when I try to run ExtractDirSearch:

```
~/git/clulab/tomcat-text (master) $ ./scripts/run_fall2020_analysis
~/git/clulab/tomcat-text ~/git/clulab/tomcat-text
Syncing ASIST data

WARNING: gsutil rsync uses hashes when modification time is not available at
both the source and destination. Your crcmod installation isn't using the
module's C extension, so checksumming will run very slowly. If this is your
first rsync since updating gsutil, this rsync can take significantly longer than
usual. For help installing the extension, please see "gsutil help crcmod".

Building synchronization state...
Starting synchronization...
Running the extraction pipeline
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/adarsh/git/clulab/tomcat-text/project
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Set current project to asist (in build file:/Users/adarsh/git/clulab/tomcat-text/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running org.clulab.asist.ExtractDirSearch /Users/adarsh/git/clulab/tomcat-text/data/study-1_2020.08
[CoreNLP] Initializing the CoreNLP pipeline ...
13:55:56.243 [run-main-0] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
13:55:56.249 [run-main-0] INFO  e.s.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
13:55:56.252 [run-main-0] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
13:55:56.254 [run-main-0] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
13:55:56.794 [run-main-0] INFO  e.s.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.5 sec].
13:55:56.795 [run-main-0] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
13:55:56.796 [run-main-0] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
13:55:57.997 [run-main-0] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.1 sec].
13:55:58.350 [run-main-0] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.4 sec].
13:55:58.918 [run-main-0] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.6 sec].
13:55:58.920 [run-main-0] INFO  e.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
13:55:59.333 [run-main-0] DEBUG e.s.n.l.t.CoreMapExpressionExtractor - Ignoring inactive rule: null
13:55:59.334 [run-main-0] DEBUG e.s.n.l.t.CoreMapExpressionExtractor - Ignoring inactive rule: temporal-composite-8:ranges
13:55:59.339 [run-main-0] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
13:56:01.016 [run-main-0] INFO  e.s.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.7 sec].
13:56:01.025 [run-main-0] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator dcoref
[CoreNLP] Completed Initialization
[error] (run-main-0) java.lang.NullPointerException
[error] java.lang.NullPointerException
[error] 	at java.io.Reader.<init>(Reader.java:78)
[error] 	at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
[error] 	at scala.io.BufferedSource.reader(BufferedSource.scala:22)
[error] 	at scala.io.BufferedSource.bufferedReader(BufferedSource.scala:23)
[error] 	at scala.io.BufferedSource.charReader$lzycompute(BufferedSource.scala:33)
[error] 	at scala.io.BufferedSource.charReader(BufferedSource.scala:31)
[error] 	at scala.io.BufferedSource.scala$io$BufferedSource$$decachedReader(BufferedSource.scala:60)
[error] 	at scala.io.BufferedSource.mkString(BufferedSource.scala:89)
[error] 	at org.clulab.asist.ExtractDirSearch$.delayedEndpoint$org$clulab$asist$ExtractDirSearch$1(ExtractDirSearch.scala:26)
[error] 	at org.clulab.asist.ExtractDirSearch$delayedInit$body.apply(ExtractDirSearch.scala:16)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at org.clulab.asist.ExtractDirSearch$.main(ExtractDirSearch.scala:16)
[error] 	at org.clulab.asist.ExtractDirSearch.main(ExtractDirSearch.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1163)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1158)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 38 s, completed Oct 28, 2020 1:56:02 PM
[INFO] [10/28/2020 13:56:02.154] [Thread-2] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

Can you try checking out the latest version of the `master` branch and running `./scripts/run_fall2020_analysis` to see if you can reproduce the error?

**Comment by adarshp** [comment]
Closed by 5132cdd168f1bccc793b40e254371f1e42c66671.
